/*
===================================================================================================
Customer Lifetime Value (LTV) by Acquisition Month (Window Function & CTE)
===================================================================================================
Business Question:
The analytics team wants to understand the long-term value of customers based on when they joined.
Calculate the total sales_amount generated by customers for each month they were acquired
('create_date' in the customer dimension table), showing the cumulative sales for each acquisition cohort over time.

Purpose for a Business Analyst:
- Acquisition Channel Optimization: Helps evaluate the long-term profitability of different
  customer acquisition strategies or channels based on the LTV of cohorts.
- Predictive Analytics Foundation: Lays the groundwork for more advanced LTV forecasting
  by providing historical cohort performance data.
- Customer Segmentation: Offers another dimension for customer segmentation, allowing
  analysis of behaviors and value based on their "age" as a customer from acquisition.

SQL Skills:
- Common Table Expressions (CTE) (for structuring intermediate results like acquisition month sales)
- Date Functions: DATE_FORMAT() (for extracting acquisition year and month)
- Aggregate Functions: SUM(), GROUP BY (for calculating total sales per acquisition month)
- Window Functions: SUM() OVER (for calculating the running/cumulative total of sales for each cohort over time)
- Data Joining: JOIN (to link sales data with customer acquisition dates)
===================================================================================================
*/
WITH AcquisitionDetails AS (
    SELECT
        s.customer_key,
        s.sales_amount,
        DATE_FORMAT(c.create_date, '%Y-%m') AS AcquisitionMonthCohort
    FROM
        gold_fact_sales s 
    LEFT JOIN
        gold_dim_customers c ON s.customer_key = c.customer_key 
    WHERE
        c.create_date IS NOT NULL   
        AND s.sales_amount IS NOT NULL 
        AND s.order_number IS NOT NULL 
),
LifetimeValue AS (
    SELECT
        customer_key,
        AcquisitionMonthCohort,
         -- Total sales (lifetime value) for each individual customer
        SUM(sales_amount) AS LifetimeSales 
    FROM
        AcquisitionDetails ad
    GROUP BY
        customer_key,
        AcquisitionMonthCohort
)
-- Step 3: Aggregate the total lifetime sales by the acquisition month cohort
SELECT
    lv.AcquisitionMonthCohort,
    -- Sum of all customer total lifetime sales for a given acquisition cohort
    SUM(LifetimeSales) AS TotalCohortLifetimeValue, 
    COUNT(DISTINCT lv.customer_key) AS NumberOfCustomersInCohort -- how many unique customers in this cohort
FROM
    LifetimeValue lv
GROUP BY
    lv.AcquisitionMonthCohort
ORDER BY
    lv.AcquisitionMonthCohort ASC; 
    